version: "3"
services:

#https://github.com/jupyter/docker-stacks

  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    
    #links:
    #  - postgres
    volumes:
          - "./notebooks:/notebooks" 
          - "./data:/data"

  #postgres:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_USER: data
  #    POSTGRES_PASSWORD: data
  #    POSTGRES_DB: data